replicaCount: 1

image:
  repository: thecodedestroyer/some-random-image-webserver
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 3000

redis:
  nameOverride: "redis"

ingress:
  annotations: {
    kubernetes.io/ingress.class: "nginx",
  }
  hosts:
    - paths:
        - path: /
          pathType: Prefix
