version: "3.9"
services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - REDIS_PORT_NUMBER=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
