version: "3.9"

services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - REDIS_PORT_NUMBER=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  webserver:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_HOST=redis
      - WEB_SERVER_VERSION=1.0.0
    ports:
      - "3000:3000"
