apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "common.fullname" . }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: WEB_SERVER_VERSION
              value: "1.0.0"
            - name: REDIS_PORT
              value: "{{ .Values.redisImported.port }}"
            - name: REDIS_HOST
              value: "{{ .Release.Name }}-{{ .Values.redis.nameOverride }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
