name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Prettier
        run: yarn prettier:lint
      - name: ESLint
        run: yarn eslint:lint
